#!/bin/bash
set -e
# curl -L "https://raw.githubusercontent.com/OfferLifted/init_dev_run/refs/heads/main/init_root_run?t=$(date +%s)" -o init_root_run
DRY="false"
if [ "$1" == "--dry" ]; then
  DRY="true"
  shift
fi

log() {
  if [ "$DRY" == "true" ]; then
    echo "DRY: $*"
  else
    echo "$*"
  fi
}

execute() {
  log "Executing: $@"
  if [ "$DRY" != "true" ]; then
    "$@"
  fi
}

log "Updating and upgrading system packages..."
execute apt update
execute apt upgrade -y

log "Installing sudo..."
execute apt install sudo -y

log "Creating user 'base'..."
execute apt install adduser -y
execute adduser base
execute usermod -aG sudo base
