#!/usr/bin/env bash
set -e

DRY="false"
if [ "$1" == "--dry" ]; then
  DRY="true"
  shift
fi

log() {
  if [ "$DRY" == "true" ]; then
    echo "DRY: $*"
  else
    echo "$*"
  fi
}

execute() {
  log "Executing: $@"
   "$@"
}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_RUNS_DIR="${SCRIPT_DIR}/script_runs"

log "Making scripts executable before running..."
for file in "${SCRIPT_RUNS_DIR}"/*; do
  execute chmod +x "$file"
done
log ""
if [ "$DRY" == "true" ]; then
  EXTRA="--dry"
else
  EXTRA=""
fi


# hardcoded to ensure correct order
execute "${SCRIPT_RUNS_DIR}/create_dirs" "$EXTRA"
execute "${SCRIPT_RUNS_DIR}/update_apt" "$EXTRA"
execute "${SCRIPT_RUNS_DIR}/set_locales" "$EXTRA"
execute "${SCRIPT_RUNS_DIR}/install_python" "$EXTRA"
execute "${SCRIPT_RUNS_DIR}/install_npm" "$EXTRA"
execute "${SCRIPT_RUNS_DIR}/install_luarocks" "$EXTRA"
execute "${SCRIPT_RUNS_DIR}/install_tools" "$EXTRA"
execute "${SCRIPT_RUNS_DIR}/install_nvim" "$EXTRA"
log ""
