#!/usr/bin/env bash
set -e
# curl -L "https://raw.githubusercontent.com/OfferLifted/init_dev_run/refs/heads/main/init_root_run?t=$(date +%s)" -o init_root_run
DRY="false"
if [ "$1" == "--dry" ]; then
  DRY="true"
  shift
fi

log() {
  if [ "$DRY" == "true" ]; then
    echo "DRY: $*"
  else
    echo "$*"
  fi
}

execute() {
  log "Executing: $@"
  if [ "$DRY" != "true" ]; then
    "$@"
  fi
}

log "Updating and upgrading system packages..."
execute apt update
execute apt upgrade -y
log ""

log "Installing sudo, adduser and temp version of git..."
execute apt install sudo -y
execute apt install adduser -y
execute apt install git -y
log ""

log "Creating user 'base'..."
execute adduser base
execute usermod -aG sudo base

BASE_HOME=$(eval echo ~base)

log "Switching to user 'base' for further setup..."
execute sudo -u base mkdir -p "$BASE_HOME/dev"
execute sudo -u base git clone https://github.com/OfferLifted/init_dev_run.git "$BASE_HOME/dev/init_dev_run"
log ""

