#!/bin/bash
set -e

DRY="false"
if [ "$1" == "--dry" ]; then
  DRY="true"
  shift
fi

log() {
  if [ "$DRY" == "true" ]; then
    echo "DRY: $*"
  else
    echo "$*"
  fi
}

execute() {
  log "Executing: $@"
  if [ "$DRY" != "true" ]; then
    "$@"
  fi
}

log "Installing python3.13 and creating nvim specific .venv at \$HOME/dev/nvim_python_env..."
execute sudo apt install python3-pip python3.13-full -y
execute python3.13 -m ensurepip --upgrade
execute bash -c 'echo "export PATH=\"$HOME/.local/bin:\$PATH\"" >> $HOME/.bashrc'
execute bash -c 'source $HOME/.bashrc'
execute cd "$HOME/dev/nvim_python_env"
execute python3.13 -m venv .venv
execute bash -c "source $HOME/dev/nvim_python_env/.venv/bin/activate && pip install pynvim && deactivate"
log ""
