#!/bin/bash
set -e

DRY="false"
if [ "$1" == "--dry" ]; then
  DRY="true"
  shift
fi

log() {
  if [ "$DRY" == "true" ]; then
    echo "DRY: $*"
  else
    echo "$*"
  fi
}

execute() {
  log "Executing: $@"
  if [ "$DRY" != "true" ]; then
    "$@"
  fi
}

log "Installing locales packages and launching config..."
execute sudo apt install locales -y
execute sudo dpkg-reconfigure locales
execute bash -c 'source $HOME/.bashrc'
log ""
