#!/bin/bash
set -e

DRY="false"
if [ "$1" == "--dry" ]; then
  DRY="true"
  shift
fi

log() {
  if [ "$DRY" == "true" ]; then
    echo "DRY: $*"
  else
    echo "$*"
  fi
}

execute() {
  log "Executing: $@"
  if [ "$DRY" != "true" ]; then
    "$@"
  fi
}

log "Adding repos, updating, upgrading and installing essentials..."
execute sudo apt update
execute sudo apt upgrade -y
execute sudo apt install software-properties-common -y

execute sudo add-apt-repository ppa:git-core/ppa -y
execute sudo add-apt-repository ppa:deadsnakes/ppa -y

execute sudo apt update
execute sudo apt upgrade -y

execute sudo apt purge git -y
execute sudo apt autoremove -y
execute sudo apt install build-essential libreadline-dev unzip curl git wget -y

execute git config --global user.name "OfferLifted"
log ""
